apiVersion: v1
kind: Service
metadata:
  name: nexus-proxy
spec:
  ports:
    - name: nexus-proxy
      nodePort: 30011
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nexus
  type: NodePort
